// Created by iWeb 3.0.2 local-build-20110115

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,232),url:'Biography_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Biography_files/stroke_1.png'},{rect:new IWRect(1,-1,653,2),url:'Biography_files/stroke_2.png'},{rect:new IWRect(654,-1,3,2),url:'Biography_files/stroke_3.png'},{rect:new IWRect(654,1,3,232),url:'Biography_files/stroke_4.png'},{rect:new IWRect(654,233,3,2),url:'Biography_files/stroke_5.png'},{rect:new IWRect(1,233,653,2),url:'Biography_files/stroke_6.png'},{rect:new IWRect(-1,233,2,2),url:'Biography_files/stroke_7.png'}],new IWSize(655,234)),shadow_1:new IWShadow({blurRadius:9,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:1.000000}),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,46),url:'Biography_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Biography_files/stroke_9.png'},{rect:new IWRect(1,-1,57,2),url:'Biography_files/stroke_10.png'},{rect:new IWRect(58,-1,2,2),url:'Biography_files/stroke_11.png'},{rect:new IWRect(58,1,2,46),url:'Biography_files/stroke_12.png'},{rect:new IWRect(58,47,2,2),url:'Biography_files/stroke_13.png'},{rect:new IWRect(1,47,57,2),url:'Biography_files/stroke_14.png'},{rect:new IWRect(-1,47,2,2),url:'Biography_files/stroke_15.png'}],new IWSize(59,48)),shadow_0:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.343333})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Biography_files/BiographyMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
